{"timestamp":"2025-10-28T10:24:40.218460Z","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-28T10:24:40.219688Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/open_weather_map_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-28T10:24:41.209891Z","level":"error","event":"HTTP error: Unauthorized","logger":"airflow.task.hooks.airflow.providers.http.hooks.http.HttpHook","filename":"http.py","lineno":314}
{"timestamp":"2025-10-28T10:24:41.210034Z","level":"error","event":"{\"cod\":401, \"message\": \"Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.\"}","logger":"airflow.task.hooks.airflow.providers.http.hooks.http.HttpHook","filename":"http.py","lineno":315}
{"timestamp":"2025-10-28T10:24:41.210154Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":972,"error_detail":[{"exc_type":"AirflowException","exc_value":"401:Unauthorized","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/bases/decorator.py","lineno":252,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/open_weather_map_dag.py","lineno":81,"name":"extract_weather_data"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/http/hooks/http.py","lineno":301,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/http/hooks/http.py","lineno":352,"name":"run_and_check"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/http/hooks/http.py","lineno":316,"name":"check_response"}],"is_group":false,"exceptions":[]},{"exc_type":"HTTPError","exc_value":"401 Client Error: Unauthorized for url: https://api.openweathermap.org//data/2.5/onecall/timemachine?lat=30.04442&lon=31.235712&dt=1761215080&appid=e305ae64603916b5e3d4dd01c678526e&units=metric","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/http/hooks/http.py","lineno":312,"name":"check_response"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/requests/models.py","lineno":1026,"name":"raise_for_status"}],"is_group":false,"exceptions":[]}]}
